Talearnt/App-Front-Talearnt

lib/common/theme.dart, lib/common/widget/test_common_widget.dart, lib/data/model/param/test_param.dart, lib/data/model/respone/test_response.dart, lib/data/repositories/test_repository.dart, lib/data/services/dio_service.dart, lib/main.dart, lib/provider/provider_set_up.dart, lib/provider/test_provider.dart, lib/view/test_page.dart, lib/view_model/test_view_model.dart, pubspec.yaml, test/widget_test.dart, web/index.html
프로젝트 초기 설정
- API 통신 모듈
- 프로젝트 구조 설계 및 상태관리
=> Talearnt 94 : 프로젝트 초기 설정

lib/provider/auth/auth_provider.dart, lib/provider/provider_set_up.dart, lib/view/auth/login_page.dart, lib/view/auth/widget/login_form.dart, lib/view/auth/widget/simple_login_form.dart
로그인 UI 화면 공통모듈로 재적용
- 로그인 UI 화면 공통모듈로 재적용
=> Talearnt 174 : 로그인 UI 화면 공통모듈로 재적용

lib/data/model/param/login_param.dart, lib/data/model/respone/failure.dart, lib/data/model/respone/token.dart, lib/data/repositories/auth_repository.dart, lib/data/services/dio_service.dart, lib/provider/auth/login_provider.dart, lib/provider/provider_set_up.dart, lib/utils/token_manager.dart, lib/view/auth/widget/login_form.dart, lib/view_model/auth_view_model.dart, pubspec.yaml
자사 로그인 처리
api 통신 예외 시 처리할 수 있게 either 추가
통신 예외 처리를 위한 post 함수 처리
Resolves : #140
=> feat : Add 자사 로그인

lib/provider/auth/login_provider.dart, lib/view/auth/widget/login_form.dart
text_field 공통 모듈로 재적용 처리
Resolves : #174
=> refactor : Simplify login 화면 공통 모듈 재적용

lib/provider/auth/kakao_provider.dart, lib/provider/provider_set_up.dart, lib/view/auth/kakao_sign_up_page.dart, lib/view/auth/widget/simple_login_form.dart
카카오 회원가입 UI
- 카카오 정보 불러와서 회원가입 할 수 있게하는 화면
Related to : #216
=> TALEARNT 216 : 카카오 회원가입 UI 

lib/provider/auth/find_password_provider.dart, lib/view/auth/find_password_page.dart, lib/view/auth/find_password_success_page.dart
이메일 건너뛸 시 에러 메세지
app bar 타이틀 수정
비밀번호 메일 전송화면 타이틀 수정
프로바이더 초기화 추가
Ref : #249
=> fix : Update 비밀번호 찾기 UI 수정

lib/data/model/param/find_id_param.dart, lib/data/model/param/send_cert_number_param.dart, lib/data/model/respone/userIdInfo.dart, lib/data/repositories/auth_repository.dart, lib/provider/auth/find_id_provider.dart, lib/provider/provider_set_up.dart, lib/utils/routes.dart, lib/view/auth/find_id_page.dart, lib/view/auth/find_id_success_page.dart, lib/view/auth/widget/login_form.dart, lib/view_model/auth_view_model.dart
에러 메세지 다이얼로그, 인증번호 관련 이슈는 남았습니다!
토스트는 아이콘 없는 공통 토스트 위젯 작업 후 일괄 적용하겠습니다.
확인 후 코멘트 부탁드리겠습니다!
=> Talearnt 122 아이디 찾기

lib/data/model/param/send_reset_password_mail_param.dart, lib/data/model/respone/send_mail_info.dart, lib/data/repositories/auth_repository.dart, lib/provider/auth/find_password_provider.dart, lib/provider/provider_set_up.dart, lib/view/auth/find_password_page.dart, lib/view/auth/find_password_success_page.dart, lib/view_model/auth_view_model.dart
비밀번호 유효성 체크 수정
비밀번호 재설정 메일 전송 api 연동 등의 기능 추가입니다.
=> Talearnt 123 비밀번호 찾기

lib/provider/auth/kakao_provider.dart, lib/view/auth/kakao_sign_up_page.dart
카카오 회원가입 UI
- 다른 정보는 받아오게
- 닉네임 텍스트 필드는 변경가능하게
-  text 공통 모듈로 재적용
- 닉네임 제외한 필드 모두 변경 불가능하게
Related to : #216
=> TALEARNT 216 : 카카오 회원가입 UI

lib/utils/routes.dart, lib/view/auth/kakao_sign_up_page.dart, lib/view/auth/sign_up_sub1_page.dart, lib/view/talent_board/match_write1_bottom_sheet.dart
이용약관 페이지 적용
- 자사 회원가입, 카카오 회원가입 이용약관 페이지 적용
Resolves : #315
=> TALEARNT 315 : 이용약관 페이지 적용

lib/provider/auth/find_id_provider.dart, lib/provider/auth/sign_up_provider.dart, lib/view/auth/sign_up_main_page.dart
인증번호 인증 후에도 타이머 다이얼로그가 나오던 오류 수정
인증번호 화면에서 나간 후에도 타이머 다이얼로그가 나오던 오류 수정
=> TALEARNT-328_타이머_오류

lib/common/widget/board_custom_app_bar.dart, lib/common/widget/button.dart, lib/constants/global_value_constants.dart, lib/data/model/respone/pagination.dart, lib/data/model/respone/talent_exchange_post.dart, lib/provider/provider_set_up.dart, lib/provider/talent_board/talent_board_provider.dart, lib/utils/routes.dart, lib/view/auth/widget/login_form.dart, lib/view/talent_board/match_board_list.dart, lib/view/talent_board/widget/board_filter_chip.dart, lib/view/talent_board/widget/board_list_card.dart, lib/view/talent_board/widget/board_list_tab_bar.dart, lib/view/talent_board/widget/board_selected_chip_list.dart, lib/view/talent_board/widget/keyword_bottom_sheet.dart, lib/view/talent_board/widget/match_board_list_card_bottom.dart, lib/view/talent_board/widget/radio_bottom_sheet.dart
키워드 데이터 select api 중지
- 초기화 함수 생성
- 등록 함수 생성
- 등록버튼 누르기 전에 목록 필터에 적용되지 않게
- radio bottom sheet 생성
- 키워드 bottom sheet 생성
- 게시물 목록 리스트 생성(목록 카드 위젯 생성)
- 게시물 목록 필터 데이터들 상수화
- 게시물 목록 필터 위젯화
Related to : #341
=> TALEARNT 341 : 매칭 게시물 리스트 UI

lib/data/model/param/talent_exchange_posts_filter_param.dart, lib/data/repositories/board_repository.dart, lib/provider/board/community_board_provider.dart, lib/provider/board/match_board_provider.dart, lib/view/board/match_board/widget/match_board_list_tab_bar.dart, lib/view/board/widget/board_custom_app_bar.dart, lib/view/home_page.dart, lib/view_model/board_view_model.dart
매칭 게시물 리스트 API - FIX
- 무한 스크롤 재처리
- talent_exchange_posts_filter_param 파일 형식 dart로 변경
- 게시물 재클릭시 처음부터 다시 부르도록
Resolves : #342
=> TALEARNT 342 : 매칭 게시물 리스트 API - FIX

lib/view/keyword/set_give_talent_keyword_page.dart, lib/view/keyword/set_interest_talent_keyword_page.dart
키워드 설정 UI 
- 검색 창에 키보드로 검색 버튼 눌렀을 때,
- 필터 결과 없으면 focus_off 처리 및 default chip list 나오도록
Ref : #258
=>  TALEARNT 258 : 키워드 설정 UI - Add

lib/common/widget/dialog.dart, lib/provider/board/match_write_provider.dart, lib/provider/provider_set_up.dart, lib/view/board/match_board/match_write2_page.dart, lib/view_model/board_view_model.dart
게시글 작성 이미지 s3 업로드 시 오류 수정
이미지 list 비동기 처리
=> Talearnt 356 게시글 이미지 업로드 오류수정

lib/constants/api_constants.dart, lib/data/model/respone/user_profile.dart, lib/data/repositories/auth_repository.dart, lib/view_model/auth_view_model.dart
사용자 프로필 API
- 사용자 프로필 API로 데이터 세팅 후,
- 키워드 세팅 페이지 판단
Resolves : #371
=> TALEARNT 371 : 사용자 프로필 API

lib/data/services/secure_storage_service.dart, lib/provider/auth/login_provider.dart, lib/provider/provider_set_up.dart, lib/utils/routes.dart, lib/view/auth/login_page.dart, lib/view/auth/widget/login_form.dart, pubspec.yaml
자동 로그인
- 로그인에서 자동 로그인 할 수 있도록
Resolves : #141
=> TALEARNT 141 : 자동 로그인

lib/common/widget/bottom_btn.dart, lib/data/model/respone/matching_detail_post.dart, lib/data/model/respone/matching_post.dart, lib/provider/board/match_board_detail_provider.dart, lib/provider/provider_set_up.dart, lib/utils/routes.dart, lib/view/board/board_list.dart, lib/view/board/match_board/match_board_detail_page.dart
매칭 게시글 상세보기 UI
- 상세보기 UI 처리
- 이미지는 URL을 받아와야하므로 API이슈에서 처리 예정
Resolves : #358
=> TALEARNT 358 : 매칭 게시글 상세보기 UI

lib/common/common_navigator.dart, lib/constants/api_constants.dart, lib/data/repositories/board_repository.dart, lib/provider/board/match_board_detail_provider.dart, lib/provider/provider_set_up.dart, lib/view/board/board_list.dart, lib/view/board/match_board/match_board_detail_page.dart, lib/view/board/match_board/match_board_image_view_detail_page.dart, lib/view/board/match_board/match_board_image_view_page.dart, lib/view_model/board_view_model.dart, pubspec.yaml
매칭 게시글 상세보기 API 
- 매칭 게시물 상세보기 API
- 이미지 미리보기 확인
Resolves : #359
=> TALEARNT 359 : 매칭 게시글 상세보기 API 

lib/data/model/param/match_board_param.dart, lib/provider/board/match_write_provider.dart, lib/view/board/match_board/match_write2_page.dart, lib/view/board/match_board/match_write_preview_page.dart, lib/view_model/board_view_model.dart
게시글 등록시 imageUrls 파라미터 비어있던 오류 수정
s3 경로 치환 시 같은 이미지인지 비교 후 치환하도록 수정
비동기 처리 추가
Ref : #356
=> fix : Update 게시글 이미지 업로드 오류수정

lib/data/model/respone/user_profile.dart, lib/data/repositories/profile_repository.dart, lib/provider/profile/profile_provider.dart, lib/provider/provider_set_up.dart, lib/view/board/match_board/match_board_detail_page.dart, lib/view/board/widget/modify_board_bottom_sheet.dart, lib/view_model/auth_view_model.dart, lib/view_model/profile_view_model.dart
매칭 게시물 상세목록 수정 바텀 탭 판단
- 상세보기 페이지에서 자기 게시물이면 수정, 삭제버튼 보이고, 아니면 보이지 않도록
Resolves : #381
=> TALEARNT 381 : 매칭 게시물 상세목록 수정 바텀 탭 판단

lib/view/board/after_filter_no_board_list_page.dart
게시물 공통 화면
- 게시물 검색 후 빈 경우 UI 디자인 수정
Resolves : #367
=> TALEARNT 367 : 게시물 공통 화면 - FIX

lib/constants/global_value_constants.dart, lib/provider/board/community_board_provider.dart, lib/view/board/community_board/widget/community_board_list_tab_bar.dart
커뮤니티 게시물 리스트 UI 
- 커뮤니티 게시물 리스트 UI 탭 수정
- 정렬 필터 제거
Resolves : #353
=> TALEARNT 353 : 커뮤니티 게시물 리스트 UI - FIX

lib/constants/api_constants.dart, lib/data/model/respone/success.dart, lib/data/repositories/board_repository.dart, lib/data/services/authorization_interceptor.dart, lib/data/services/dio_service.dart, lib/provider/board/match_edit_provider.dart, lib/provider/board/match_write_provider.dart, lib/provider/provider_set_up.dart, lib/utils/routes.dart, lib/view/board/match_board/match_board_detail_page.dart, lib/view/board/match_board/match_edit1_bottom_sheet.dart, lib/view/board/match_board/match_edit1_page.dart, lib/view/board/match_board/match_edit2_page.dart, lib/view/board/match_board/match_edit_editor_toolbar.dart, lib/view/board/match_board/match_edit_preview_page.dart, lib/view/board/match_board/match_write2_page.dart, lib/view/board/match_board/match_write_preview_page.dart, lib/view/board/widget/modify_board_bottom_sheet.dart, lib/view_model/board_view_model.dart, lib/view_model/keyword_view_model.dart
매칭 게시글 수정 UI
매칭 게시글 수정 api
이미지 업로드 시 최대 용량 제한에서 개수 제한으로 변경
=> Talearnt 394 매칭 게시글 수정

lib/provider/board/match_board_detail_provider.dart, lib/view/board/match_board/match_board_detail_page.dart, lib/view/board/match_board/match_board_image_view_detail_page.dart, lib/view/board/match_board/match_board_image_view_page.dart
S3 이미지 Image.network로 보여지도록 수정
Ref : #404
=> fix : Update 이미지 관련 오류 수정

lib/utils/routes.dart, lib/view/auth/login_page.dart, lib/view/auth/sign_up_main_page.dart, lib/view/auth/sign_up_success_page.dart, lib/view/auth/widget/login_form.dart, lib/view/board/match_board/match_write1_page.dart, lib/view/board/match_board/match_write2_page.dart, lib/view/home_page.dart, lib/view/keyword/set_talent_keyword_success_page.dart, lib/view_model/profile_view_model.dart
기본 라우트 메인으로 변경
로그인 라우트 /login으로 변경
Ref : #409
=> fix : Update 메인 라우트 정리

lib/constants/api_constants.dart, lib/data/model/param/community_board_list_search_param.dart, lib/data/model/respone/community_board.dart, lib/data/model/respone/pagination.dart, lib/data/repositories/board_repository.dart, lib/provider/board/community_board_provider.dart, lib/provider/board/match_board_provider.dart, lib/provider/provider_set_up.dart, lib/view/board/board_list.dart, lib/view/board/community_board/widget/community_board_list_card.dart, lib/view/board/community_board/widget/community_board_list_card_bottom.dart, lib/view/board/community_board/widget/community_board_list_tab_bar.dart, lib/view/board/widget/board_custom_app_bar.dart, lib/view_model/board_view_model.dart
커뮤니티 게시물 목록 API
- 게시물 목록 API
- 스크롤 처리 및 TAB 바꿀때마다 postType 달라지게
- \+ tabBar 디자인 수정
Resolves : #354
=>  TALEARNT 354 : 커뮤니티 게시물 목록 API

lib/data/services/authorization_interceptor.dart, lib/provider/board/community_write_provider.dart, lib/provider/provider_set_up.dart, lib/view/board/community_board/community_write2_page.dart, lib/view/board/community_board/community_write_preview_page.dart, lib/view/board/match_board/match_edit2_page.dart, lib/view/board/match_board/match_edit_preview_page.dart, lib/view/board/match_board/match_write2_page.dart, lib/view/board/match_board/match_write_preview_page.dart, lib/view_model/board_view_model.dart
커뮤니티 게시글 등록 시 에러 수정
type으로 매칭/커뮤니티, 등록/수정 구분 되도록 수정
Resolves : #410
=> TALEARNT 410 : 커뮤니티 게시글 등록 에러수정

lib/constants/api_constants.dart, lib/data/model/respone/community_detail_board.dart, lib/data/repositories/board_repository.dart, lib/provider/board/community_board_detail_provider.dart, lib/provider/board/community_write_provider.dart, lib/provider/provider_set_up.dart, lib/utils/routes.dart, lib/view/board/board_list.dart, lib/view/board/community_board/community_board_detail_page.dart, lib/view/board/community_board/community_board_image_view_detail_page.dart, lib/view/board/community_board/community_board_image_view_page.dart, lib/view/board/community_board/community_write_preview_page.dart, lib/view/board/community_board/widget/community_detail_board_bottom.dart, lib/view_model/board_view_model.dart
커뮤니티 게시물 상세보기 UI 및 API
- 상세 게시물 UI 및 API
Resolves : #411
=> TALEARNT 411 : 커뮤니티 게시물 상세보기 UI 및 API

lib/provider/home/home_provider.dart, lib/provider/provider_set_up.dart, lib/view/board/no_board_list_page.dart, lib/view/home_page.dart, lib/view/widget/home_board_card.dart, lib/view_model/board_view_model.dart
맞춤 매칭 게시글 API 추가
신규 매칭 게시글 API 추가
BEST 커뮤니티 게시글 API 추가
Resolve : #407
=> Talearnt 407 메인 페이지 api

lib/constants/api_constants.dart, lib/data/model/param/match_board_list_search_param.dart, lib/data/model/respone/match_board.dart, lib/data/repositories/board_repository.dart, lib/provider/board/match_board_provider.dart, lib/provider/home/home_provider.dart, lib/view/board/after_filter_no_board_list_page.dart, lib/view/board/board_list.dart, lib/view/board/match_board/widget/match_board_list_card.dart, lib/view/board/match_board/widget/match_board_list_card_bottom.dart, lib/view/board/match_board/widget/match_board_list_tab_bar.dart, lib/view/board/widget/board_custom_app_bar.dart, lib/view/home_page.dart, lib/view/widget/home_board_card.dart, lib/view_model/board_view_model.dart
매칭 게시물 리스트 API
- 매칭 게시물 리스트 api 수정으로 인한 param 수정
- 게시물 명칭 통일성을 위한 매칭 게시물 함수 및 파라미터 명칭 수정
Ref : #342
=>  TALEARNT 342 : 매칭 게시물 리스트 API

lib/data/model/respone/user_id_info.dart, lib/provider/auth/find_id_provider.dart, lib/provider/board/community_write_provider.dart, lib/provider/board/match_board_provider.dart, lib/provider/board/match_edit_provider.dart, lib/provider/board/match_write_provider.dart, lib/view/auth/find_id_page.dart, lib/view/auth/find_id_success_page.dart, lib/view/board/match_board/match_edit2_page.dart, lib/view/board/match_board/match_write_editor_toolbar.dart, lib/view/board/match_board/widget/match_board_selected_chip_list.dart, lib/view/home_page.dart, lib/view_model/auth_view_model.dart, lib/view_model/board_view_model.dart, lib/view_model/keyword_view_model.dart
테스트 중 발견한 오류 일괄 수정
· 메인화면 게시글 상세보기 api 추가
· 메인화면 맞춤 게시글, 신규 게시글, 베스트 게시글 목록 더보기 api 추가
· 게시글 수정 시 이미지 순서 보장되도록 수정
· 게시글 작성 시 게시글 제목 및 내용 글자수 체크 로직 추가
· 게시글 이미지 업로드 시 압축 방식 변경
· 게시글 이미지 업로드 시 최대 개수 체크 수정 및 이미지 삭제 시 개수 반영되도록 수정
· 아이디 찾기 시 response 값 에러 수정
Resoluve : #417
=> Talearnt 417 테스트 오류 수정

lib/view/board/community_board/widget/community_board_list_card_bottom.dart, lib/view/board/community_board/widget/community_detail_board_bottom.dart
feat : 커뮤니티 댓글수 적용
커뮤니티 목록 및 상세보기 댓글 수 적용
Resolves : #454
Ref : #354, #411
=> TALEARNT 454 : 커뮤니티 댓글수 적용

lib/common/widget/common_bottom_navigation_bar.dart, lib/provider/common/common_provider.dart, lib/view/board/board_list.dart, lib/view/board/community_board/community_replies.dart, lib/view/board/widget/board_custom_app_bar.dart, lib/view/home_page.dart, lib/view/profile/profile_page.dart, lib/view/widget/home_board_card.dart
fix : APK TEST 개선사항
Resolves : #445
=> TALEARNT 445 : APK TEST 개선사항

lib/common/widget/common_bottom_navigation_bar.dart, lib/view/home_bottom_sheet.dart
· home page 메뉴바 글쓰기 터치 시 바텀시트로 매칭, 커뮤니티 게시글 선택하도록 변경
Resolve : #470
=> fix : 게시글 작성 분기 추가

lib/view/home_page.dart
서버에 반복적인 API 요청을 하던 오류 수정
비동기처리에서 병렬 구조로 API 요청하도록 수정
Resolve : #477
=> fix : 메인 페이지 API 오류수정

lib/constants/global_value_constants.dart, lib/data/repositories/board_repository.dart, lib/provider/board/community_edit_provider.dart, lib/provider/provider_set_up.dart, lib/utils/routes.dart, lib/view/board/community_board/community_edit1_page.dart, lib/view/board/community_board/community_edit2_page.dart, lib/view/board/community_board/community_edit_editor_toolbar.dart, lib/view/board/community_board/community_edit_preview_page.dart, lib/view/board/community_board/community_write_preview_page.dart, lib/view/board/widget/modify_board_bottom_sheet.dart, lib/view_model/board_view_model.dart
커뮤니티 게시글 라우트 수정
커뮤니티 게시글 수정 로딩, 토스트추가
Resolve : #419
=> Talearnt 419 커뮤니티 게시물 수정 UI 및 api

lib/provider/board/community_write_provider.dart, lib/provider/board/match_edit_provider.dart, lib/provider/board/match_write_provider.dart, lib/view/board/community_board/community_board_detail_page.dart, lib/view/board/community_board/community_write2_page.dart, lib/view/board/community_board/community_write_editor_toolbar.dart, lib/view/board/community_board/community_write_preview_page.dart, lib/view/board/match_board/match_board_detail_page.dart, lib/view/board/match_board/match_edit2_page.dart, lib/view/board/match_board/match_edit_editor_toolbar.dart, lib/view/board/match_board/match_edit_preview_page.dart, lib/view/board/match_board/match_write2_page.dart, lib/view/board/match_board/match_write_preview_page.dart, pubspec.yaml
fix : 게시물 에디터 관련 수정
게시물 에디터 사진 클릭 시 반응 제거
게시물 수정/글쓰기 사진 넣으면 탭 추가
라이브러리 버전 업을 통한 에디터 위젯 명칭 설정
Resolves : #482
=> TALEARNT 482 : 게시물 에디터 관련 수정

lib/view/home_page.dart, lib/view/widget/home_board_card.dart
fix : Update 메인 페이지 UI
화면 가로폭이 작아서 닉네임이나 글자들 잘리는 현상
...으로 처리
Resolves : #406
=> TALEARNT 406 : 메인 페이지 UI

lib/constants/api_constants.dart, lib/data/model/param/send_reset_password_mail_param.dart, lib/data/repositories/auth_repository.dart, lib/view/auth/find_id_page.dart, lib/view/auth/find_password_page.dart, lib/view_model/auth_view_model.dart
fix : Update 아이디 비밀번호 찾기 오류 수정
비밀번호 찾기 api 수정
아이디 찾기 인증번호 발송 시 fail 뜨면 '인증번호 요청했습니다' toast 나오지 않게
Resolves : #490
Ref : #122, #123
=> TALEARNT 490 : 아이디 비밀번호 찾기 오류 수정

lib/constants/api_constants.dart, lib/data/model/respone/notice_detail.dart, lib/data/repositories/profile_repository.dart, lib/provider/profile/profile_provider.dart, lib/utils/routes.dart, lib/view/profile/event_notice_page.dart, lib/view/profile/no_event_notice_page.dart, lib/view/profile/notice_detail_page.dart, lib/view/profile/widget/event_tab.dart, lib/view/profile/widget/notice_tab.dart, lib/view_model/profile_view_model.dart
feat : Add 공지사항 상세보기 UI 및 API
이벤트/공지사항 위젯 나누기
공지사항 상세보기 UI 및 API 연결
Resolves : #492
=>  TALEARNT 492 : 공지사항 상세보기 UI 및 API

lib/common/widget/default_text_field.dart, lib/constants/api_constants.dart, lib/data/model/param/kakao_sign_up_param.dart, lib/data/model/respone/kakao_login_result.dart, lib/data/model/respone/kakao_sign_up_user_info.dart, lib/data/repositories/auth_repository.dart, lib/main.dart, lib/provider/auth/kakao_provider.dart, lib/provider/provider_set_up.dart, lib/utils/routes.dart, lib/view/auth/kakao_sign_up_page.dart, lib/view/auth/login_page.dart, lib/view/auth/sign_up_main_page.dart, lib/view/auth/widget/simple_login_form.dart, lib/view_model/auth_view_model.dart, lib/view_model/keyword_view_model.dart, lib/view_model/profile_view_model.dart, pubspec.yaml
feat : Add 카카오 로그인 및 회원가입 API
로그인 API 진행하여 유저 정보 없으면 회원가입 할 수 있도록
로그인 후 키워드 세팅 안되어있으면 세팅 할 수 있도록
Resolves : #139
=> TALEARNT 139 : 카카오 로그인 및 회원가입 API

lib/constants/api_constants.dart, lib/data/repositories/board_repository.dart, lib/data/repositories/notification_repository.dart, lib/data/services/dio_service.dart, lib/view/alarm/alarm_page.dart, lib/view/profile/widget/profile_setting_section.dart, lib/view_model/auth_view_model.dart, lib/view_model/notification_view_model.dart
자동 로그인일때만 fcm 토큰 넘기도록 수정
로그아웃 시 fcm 토큰 삭제 요청
Resolve : #496
=> Talearnt 496 알림 잔여작업

lib/view/home_page.dart
읽지 않은 알림이 존재할 경우 알림 아이콘 변경되도록 수정
Resolve : #496
=> feat : Update 알림 잔여작업

lib/constants/api_constants.dart, lib/data/model/param/recuruiting_param.dart, lib/data/model/respone/match_board.dart, lib/data/repositories/board_repository.dart, lib/data/services/dio_service.dart, lib/provider/board/match_board_detail_provider.dart, lib/provider/board/match_board_provider.dart, lib/view/board/match_board/match_board_detail_page.dart, lib/view_model/board_view_model.dart
본인 게시글 상세페이지 이동 시 모집중/모집마감 토글로 변경되도록 수정
모집구분 변경 시 API 추가
모집구분 변경 시 게시글목록 반영되도록 수정
Ref : #499
=> feat : Update 매칭게시글 모집마감

lib/view/home_page.dart
=> feat : Add 푸터
